image: php:${PHP_VERSION}-fpm

variables:
  XDEBUG_MODE: coverage
  PHP_VERSION: 8.1 # Default PHP version

stages:
  - Build
  - Code Quality
  - Test

before_script:
  - apt-get -qq update
  - apt-get -qq install zip unzip git libicu-dev libpq-dev libzip-dev libsqlite3-dev zlib1g-dev -y
  - docker-php-ext-install sockets pgsql pdo_pgsql pdo_mysql > /dev/null
  - pecl install xdebug && docker-php-ext-enable xdebug
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
  - composer require --dev phpunit/phpunit phpunit/php-code-coverage

composer:
  stage: Build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
  script:
    - composer install
  artifacts:
    expire_in: 1 day
    paths:
      - vendor/

code_quality:
  stage: Code Quality
  script:
    - vendor/bin/php-cs-fixer fix -vvv --dry-run --show-progress=dots

unused_scanner:
  stage: Code Quality
  dependencies:
    - composer
  script:
    - vendor/bin/unused_scanner unused-scanner.php

unit_test:
  stage: Test
  variables:
    PHP_VERSION: ${MATRIX_PHP_VERSION}
  script:
    - vendor/bin/phpunit
  artifacts:
    reports:
      junit:
        - build/report.junit.xml
      coverage_report:
        coverage_format: cobertura
        path: build/logs/clover.xml
  parallel:
    matrix:
      - MATRIX_PHP_VERSION: ["8.1", "8.2", "8.3"]