name: CI

on:
  push:
    branches: ['**']
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  composer:
    name: Composer install
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
          coverage: none
      - run: composer install --prefer-dist --no-progress --no-interaction --ignore-platform-reqs
      - uses: actions/upload-artifact@v4
        with:
          name: vendor
          path: vendor
          retention-days: 1

  code-style:
    name: Code Style
    needs: composer
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
          coverage: none
      - uses: actions/download-artifact@v4
        with:
          name: vendor
          path: vendor
      - run: chmod +x vendor/bin/*
      - run: vendor/bin/php-cs-fixer fix --dry-run --diff --verbose

  test:
    name: PHPUnit
    needs: composer
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
          coverage: none
      - uses: actions/download-artifact@v4
        with:
          name: vendor
          path: vendor
      - run: chmod +x vendor/bin/*
      - run: vendor/bin/phpunit --testdox --log-events-verbose-text php://stdout
